"""initial schema

Revision ID: 41cc47319b05
Revises:
Create Date: 2026-09-07 23:10:49.683987

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41cc47319b05"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_fa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bank_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last4", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_last4"), "account", ["last4"], unique=False)
    op.create_table(
        "appsetting",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_fa", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "keywordrule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sa.Enum("DEPOSIT", "WITHDRAWAL", name="direction"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keywordrule_keyword"), "keywordrule", ["keyword"], unique=False)
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pushsubscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fcm_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pushsubscription_fcm_token"), "pushsubscription", ["fcm_token"], unique=True
    )
    op.create_table(
        "smspattern",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_match", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_regex", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_unit", sa.Enum("RIAL", "TOMAN", name="amountunit"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("limit_cents", sa.Integer(), nullable=False),
        sa.Column("month_jalali", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchantcategorymap",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchantcategorymap_merchant_key"),
        "merchantcategorymap",
        ["merchant_key"],
        unique=True,
    )
    op.create_table(
        "smsingestattempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("matched_pattern_id", sa.Integer(), nullable=True),
        sa.Column(
            "parse_status", sa.Enum("PARSED", "UNPARSED", name="parsestatus"), nullable=False
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=True),
        sa.Column("direction", sa.Enum("DEPOSIT", "WITHDRAWAL", name="direction"), nullable=True),
        sa.Column("account_last4", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=True),
        sa.Column("merchant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_pattern_id"],
            ["smspattern.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("direction", sa.Enum("DEPOSIT", "WITHDRAWAL", name="direction"), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source", sa.Enum("SMS", "MANUAL", "SPLIT_SETTLEMENT", name="txsource"), nullable=False
        ),
        sa.Column("ingest_attempt_id", sa.Integer(), nullable=True),
        sa.Column("merchant_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("dedup_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transaction_dedup_hash"), "transaction", ["dedup_hash"], unique=False)
    op.create_table(
        "split",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.Enum("I_PAID", "THEY_PAID", name="splitmode"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_table(
        "splitshare",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("line_item", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["split.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "debt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_share_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "direction", sa.Enum("OWED_TO_ME", "I_OWE", name="debtdirection"), nullable=False
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("amount_settled_cents", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("OPEN", "PARTIAL", "SETTLED", name="debtstatus"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_share_id"],
            ["splitshare.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("split_share_id"),
    )
    op.create_table(
        "debtpayment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("debt_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("settled_at", sa.DateTime(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["debt_id"],
            ["debt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("debtpayment")
    op.drop_table("debt")
    op.drop_table("splitshare")
    op.drop_table("split")
    op.drop_index(op.f("ix_transaction_dedup_hash"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_table("smsingestattempt")
    op.drop_index(op.f("ix_merchantcategorymap_merchant_key"), table_name="merchantcategorymap")
    op.drop_table("merchantcategorymap")
    op.drop_table("budget")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_table("smspattern")
    op.drop_index(op.f("ix_pushsubscription_fcm_token"), table_name="pushsubscription")
    op.drop_table("pushsubscription")
    op.drop_table("person")
    op.drop_index(op.f("ix_keywordrule_keyword"), table_name="keywordrule")
    op.drop_table("keywordrule")
    op.drop_table("category")
    op.drop_table("appsetting")
    op.drop_index(op.f("ix_account_last4"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
