/**
 * Settings is an admin screen the design bundle doesn't cover, so its copy
 * lives here rather than in the design string tables.
 */
export const S = {
  fa: {
    title: "تنظیمات",
    logout: "خروج از حساب",

    notifications: "اعلان‌ها",
    pushReady: "سرور برای ارسال اعلان آماده است",
    pushNotReady: "Firebase روی سرور پیکربندی نشده — اعلان‌ها غیرفعال است",
    enablePush: "فعال‌سازی اعلان در این مرورگر",
    firebaseIncomplete: "پیکربندی Firebase در frontend/src/lib/firebaseConfig.ts هنوز تکمیل نشده.",
    pushEnabled: "اعلان‌ها فعال شد",
    reasonNotConfigured: "پیکربندی Firebase کامل نیست — به README مراجعه کنید",
    reasonPermissionDenied: "اجازه اعلان داده نشد",
    reasonNoServiceWorker: "مرورگر از Service Worker پشتیبانی نمی‌کند",
    reasonError: "خطا در فعال‌سازی اعلان",
    thresholdLabel: "آستانه هشدار دسته‌بندی‌نشده‌ها",
    summaryLabel: "خلاصه دوره‌ای",
    off: "خاموش",
    weekly: "هفتگی",
    monthly: "ماهانه",
    saveSettings: "ذخیره تنظیمات",

    webhookTitle: "توکن Webhook",
    webhookHint: "برای اتصال اپ فورواردر پیامک (MacroDroid/Tasker) — به README مراجعه کنید",
    generateToken: "تولید توکن جدید",
    tokenOnce: "این توکن فقط یک‌بار نمایش داده می‌شود — همین حالا کپی کنید.",

    patternsTitle: "الگوهای پیامک بانکی",
    patternsHint: "هر بانک یک الگوی regex دارد — ویرایش یا افزودن الگوی جدید",
    delete: "حذف",
    testWithSample: "آزمایش با متن نمونه",
    samplePlaceholder: "متن نمونه پیامک را اینجا بچسبانید",
    runTest: "اجرای آزمایش",
    addPatternLabel: "افزودن الگوی جدید",
    namePlaceholder: "نام (مثلاً بانک ملی)",
    senderPlaceholder: "sender match",
    regexPlaceholder: "regex با named groups: amount, type, account, datetime, merchant",
    addPattern: "افزودن الگو",

    keywordsTitle: "کلیدواژه‌های واریز/برداشت",
    keywordsHint: "کدام کلمات یعنی واریز و کدام یعنی برداشت",
    withdrawal: "برداشت",
    deposit: "واریز",
    newKeyword: "کلیدواژه جدید",
    addKeyword: "افزودن کلیدواژه",

    general: "عمومی",
    generalHint: "زبان و شکل ارقام — روی سرور ذخیره می‌شود",
    defaultLang: "زبان پیش‌فرض",
    digitStyle: "شکل ارقام",
    persianDigits: "فارسی",
    latinDigits: "لاتین",
    persian: "فارسی",
    english: "انگلیسی",

    accounts: "حساب‌ها",
    accountsHint: "حساب‌هایی که پیامک‌هایشان خوانده می‌شود",
    accountNameFa: "نام (فارسی)",
    accountNameEn: "نام (انگلیسی)",
    bankName: "نام بانک",
    last4: "۴ رقم آخر",
    active: "فعال",
    inactive: "غیرفعال",
    addAccount: "افزودن حساب",

    categories: "دسته‌بندی‌ها",
    categoriesHint: "دسته‌ها، رنگ و ترتیبشان",
    nameFa: "نام فارسی",
    nameEn: "نام انگلیسی",
    icon: "آیکن",
    color: "رنگ",
    sortOrder: "ترتیب",
    parent: "دستهٔ والد",
    noParent: "بدون والد",
    addCategory: "افزودن دسته",

    budgets: "بودجه‌ها",
    budgetsHint: "سقف ماهانهٔ هر دسته",
    limitToman: "سقف (تومان)",
    monthJalali: "ماه (مثلاً ۱۴۰۵-۰۶)",
    everyMonth: "همهٔ ماه‌ها",
    addBudget: "افزودن بودجه",

    peopleTitle: "افراد",
    peopleHint: "کسانی که هزینه با آن‌ها تقسیم می‌شود",
    personName: "نام",
    contactNote: "یادداشت تماس",
    addPerson: "افزودن فرد",

    save: "ذخیره",
    cancel: "انصراف",
    edit: "ویرایش",
    remove: "حذف",
    confirmRemove: "مطمئنید؟",
    none: "چیزی ثبت نشده",
    disablePush: "غیرفعال‌سازی اعلان روی این مرورگر",
    pushDisabled: "اعلان‌ها روی این دستگاه غیرفعال شد",
    iconCredit: "آیکن‌ها از",
  },
  en: {
    title: "Settings",
    logout: "Sign out",

    notifications: "Notifications",
    pushReady: "The server is ready to send notifications",
    pushNotReady: "Firebase is not configured on the server — notifications are off",
    enablePush: "Enable notifications in this browser",
    firebaseIncomplete: "Firebase config in frontend/src/lib/firebaseConfig.ts is still incomplete.",
    pushEnabled: "Notifications enabled",
    reasonNotConfigured: "Firebase config is incomplete — see the README",
    reasonPermissionDenied: "Notification permission was denied",
    reasonNoServiceWorker: "This browser does not support service workers",
    reasonError: "Could not enable notifications",
    thresholdLabel: "Uncategorized alert threshold",
    summaryLabel: "Periodic summary",
    off: "Off",
    weekly: "Weekly",
    monthly: "Monthly",
    saveSettings: "Save settings",

    webhookTitle: "Webhook token",
    webhookHint: "For the SMS forwarder app (MacroDroid/Tasker) — see the README",
    generateToken: "Generate a new token",
    tokenOnce: "This token is shown once — copy it now.",

    patternsTitle: "Bank SMS patterns",
    patternsHint: "One regex per bank — edit or add a new pattern",
    delete: "Delete",
    testWithSample: "Test with sample text",
    samplePlaceholder: "Paste a sample SMS here",
    runTest: "Run test",
    addPatternLabel: "Add a new pattern",
    namePlaceholder: "Name (e.g. Bank Melli)",
    senderPlaceholder: "sender match",
    regexPlaceholder: "regex with named groups: amount, type, account, datetime, merchant",
    addPattern: "Add pattern",

    keywordsTitle: "Deposit / withdrawal keywords",
    keywordsHint: "Which words mean money in, and which mean money out",
    withdrawal: "Withdrawal",
    deposit: "Deposit",
    newKeyword: "New keyword",
    addKeyword: "Add keyword",

    general: "General",
    generalHint: "Language and digit shape — stored on the server",
    defaultLang: "Default language",
    digitStyle: "Digit style",
    persianDigits: "Persian",
    latinDigits: "Latin",
    persian: "Persian",
    english: "English",

    accounts: "Accounts",
    accountsHint: "The accounts whose messages get read",
    accountNameFa: "Name (Persian)",
    accountNameEn: "Name (English)",
    bankName: "Bank name",
    last4: "Last 4 digits",
    active: "Active",
    inactive: "Inactive",
    addAccount: "Add account",

    categories: "Categories",
    categoriesHint: "Categories, their colour and order",
    nameFa: "Persian name",
    nameEn: "English name",
    icon: "Icon",
    color: "Colour",
    sortOrder: "Order",
    parent: "Parent category",
    noParent: "No parent",
    addCategory: "Add category",

    budgets: "Budgets",
    budgetsHint: "Monthly ceiling per category",
    limitToman: "Limit (Toman)",
    monthJalali: "Month (e.g. 1405-06)",
    everyMonth: "Every month",
    addBudget: "Add budget",

    peopleTitle: "People",
    peopleHint: "Who you split expenses with",
    personName: "Name",
    contactNote: "Contact note",
    addPerson: "Add person",

    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Delete",
    confirmRemove: "Sure?",
    none: "Nothing yet",
    disablePush: "Turn off notifications on this browser",
    pushDisabled: "Notifications turned off on this device",
    iconCredit: "Icons by",
  },
} as const;

export type SettingsStrings = { readonly [K in keyof (typeof S)["fa"]]: string };
